### ISSUE TITLE
蚂蚁金服加入邀请

### ISSUE THREAD

**Issue by nediya** [No-Github/Digital-Privacy#1]
你好，我们是蚂蚁金服大安全，我们认为你在github中的内容与我们的工作具有很高的匹配度，能否方便留一个联系方式（电话，邮箱等均可），欢迎联系我：dengyuan.dengyuan@antfin.com，非常感谢～～
附上职位说明：
1、与世界一流的平台安全、数据安全的专家合作，面向未来建设云+IOT时代的基础安全能力，竖立行业标准；
2、负责全域基础安全数据体系和应用产品数据体系的建设，通过离线和实时的混合计算，让数据成为基础安全新的驱动力；
3、参与基础安全平台的基础架构和技术体系的规划和落地，面向未来构建云、网络、端的防御中台；

职位描述
1、有从事分布式数据存储与计算平台应用开发经验，熟悉Hadoop生态相关技术并有相关开发经验，有Spark/Flink的开发经验尤佳；
2、较为丰富的数据仓库及数据平台的架构经验，精通数据仓库建模及ETL设计开发，有较为系统的海量数据性能处理经验；具备一定的JAVA、Python语言的开发能力；
3、熟悉基础的计算机原理，包括操作系统、TCP/IP网络协议、计算机组成等；
4、具有良好的逻辑思维能力、沟通协作能力，自我驱动，具备突出的分析问题和解决问题的能力；
5、有网络攻防、数据安全、嵌入式数据研发相关经验者优先。

**Comment by No-Github** [comment]
很感兴趣，电话不方便留，请发邮件至 D2hwakH7BS5E@protonmail.com 详谈，见谅
